name: daytoday
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  sqflite: ^2.2.4+1
  path_provider: ^2.0.12
  intl: ^0.18.0
  flutter_launcher_icons: ^0.11.0
  url_launcher: ^6.1.8
  googleapis: ^10.0.0
  googleapis_auth: ^1.3.1
  pdf: ^3.8.4
  flutter_pdfview: ^1.2.5
  google_sign_in: ^5.4.4
  firebase_core: ^2.4.1
  flutter_native_splash: ^2.2.16
  shared_preferences: ^2.0.18
  local_auth: ^2.1.6
  excel: ^2.0.1
  device_info_plus: ^8.1.0
  permission_handler: ^10.2.0
  file_picker: ^5.2.5
  http: ^0.13.6
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0

flutter_native_splash:
  color: "#6666ff"
  fullscreen: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/